config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users do
    member do
      get :likes
    end
  end

  resources :posts do
    resource :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many_attached :portraits

  validates :title, presence: true, length: { maximum: 10 }
  validates :subject, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 255 }
  validates :portraits, presence: true

  has_many :favorites, dependent: :destroy
  has_many :likers, through: :favorites, source: :user

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 10 }
  validates :nickname, presence: true, length: { maximum: 10 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :posts, dependent: :destroy
  has_one_attached :profile_image

  has_many :favorites, dependent: :destroy
  has_many :likes, through: :favorites, source: :post

  def favorite(post)
    unless self == post.user
      self.favorites.find_or_create_by(post_id: post.id)
    end
  end

  def unfavorite(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end
  
  def like?(post)
    self.likes.include?(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  def create
    post = Post.find(params[:post_id])
    current_user.favorite(post)
    flash[:danger] = 'お気に入りに追加しました。'
    redirect_back(fallback_location: root_path)
  end

  def destroy
    post = Post.find(params[:post_id])
    current_user.unfavorite(post)
    flash[:success] = 'お気に入り解除しました。'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.order(id: :desc).page(params[:page]).per(5)
  end
  def show
    @post = Post.find(params[:id])
  end
  def new
    @post = Post.new
  end
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '口コミが投稿されました！'
      redirect_to @post
      # showルーティング（posts/:id）に飛ばす
    else
      @posts = current_user.posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = '投稿に失敗しました。'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = '口コミ内容が更新されました'
      redirect_to @post
    else
      flash[:danger] = '口コミ内容の更新に失敗しました。'
      render :edit
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:danger] = '口コミを削除しました。'
    redirect_to root_url
  end

  private
  
  def post_params
    params.require(:post).permit(:content, :title, :subject, portraits: [])
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      # ログイン状態を維持する
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]
  def index
    @users = User.order(id: :desc).page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = '登録ありがとうございます！'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザーの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザ-を情報を更新しました。'
      redirect_to @user
    else
      flash[:danger] = 'ユーザーの情報更新に失敗しました。'
      render :edit
    end
  end

  def likes
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page])
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :nickname, :profile_image, :email, :password,:password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-2">
  <div class="container px-0">
    <div class="footer-logo text-center mb-4">
      <img src="/assets/logo.png" alt="ロゴ" class="pt-3">
    </div>
    <ul class="footer-list text-center mt-4 pb-3 pl-0">
      <li class="nav-item"><%= link_to 'トップページ', root_path, class: 'nav-link' %>
    <% if logged_in? %>
      <li class="nav-item"><%= link_to 'マイページ', user_path(current_user), class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to '口コミ一覧', posts_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to '新規投稿', new_post_path, class: 'nav-link' %></li>
    <% else %>
      <li class="nav-item"><%= link_to '会員登録', signup_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
    <% end %>
    </ul>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header class='sticky-top'>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgb(211, 210, 208);">
    <div class="container">
      <a class="navbar-brand mx-0 py-0" href="/"><img src="/assets/logo.png" alt="logo"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <div class="navbar-nav mr-auto">
          <div class="dropdown">
            <button type="button" class="btn dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">北海道</button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">            
              <li><a class="dropdown-item" href="#">北海道</a></li>
            </ul>
          </div>
          
          <div class="dropdown">
            <button type="button" class="btn dropdown-toggle" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">東北</button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
              <li><a class="dropdown-item" href="#">青森</a></li>
              <li><a class="dropdown-item" href="#">岩手</a></li>
              <li><a class="dropdown-item" href="#">宮城</a></li>
              <li><a class="dropdown-item" href="#">秋田</a></li>
              <li><a class="dropdown-item" href="#">山形</a></li>
              <li><a class="dropdown-item" href="#">福島</a></li>
            </ul>
          </div>
          <div class="dropdown">
            <button type="button" class="btn dropdown-toggle" id="dropdownMenuButton3" data-bs-toggle="dropdown" aria-expanded="false">関東</button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton3">
              <li><a class="dropdown-item" href="#">茨城</a></li>
              <li><a class="dropdown-item" href="#">栃木</a></li>
              <li><a class="dropdown-item" href="#">群馬</a></li>
              <li><a class="dropdown-item" href="#">埼玉</a></li>
              <li><a class="dropdown-item" href="#">千葉</a></li>
              <li><a class="dropdown-item" href="#">東京</a></li>
              <li><a class="dropdown-item" href="#">神奈川</a></li>
            </ul>
          </div>
          <div class="dropdown">
            <button type="button" class="btn dropdown-toggle" id="dropdownMenuButton4" data-bs-toggle="dropdown" aria-expanded="false">中部</button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton4">
              <li><a class="dropdown-item" href="#">新潟</a></li>
              <li><a class="dropdown-item" href="#">富山</a></li>
              <li><a class="dropdown-item" href="#">石川</a></li>
              <li><a class="dropdown-item" href="#">福井</a></li>
              <li><a class="dropdown-item" href="#">山梨</a></li>
              <li><a class="dropdown-item" href="#">長野</a></li>
              <li><a class="dropdown-item" href="#">岐阜</a></li>
              <li><a class="dropdown-item" href="#">静岡</a></li>
              <li><a class="dropdown-item" href="#">愛知</a></li>
              <li><a class="dropdown-item" href="#">三重</a></li>
            </ul>
          </div>
          <div class="dropdown">
            <button type="button" class="btn dropdown-toggle" id="dropdownMenuButton5" data-bs-toggle="dropdown" aria-expanded="false">近畿</button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton5">
              <li><a class="dropdown-item" href="#">三重</a></li>
              <li><a class="dropdown-item" href="#">滋賀</a></li>
              <li><a class="dropdown-item" href="#">京都</a></li>
              <li><a class="dropdown-item" href="#">大阪</a></li>
              <li><a class="dropdown-item" href="#">兵庫</a></li>
              <li><a class="dropdown-item" href="#">奈良</a></li>
              <li><a class="dropdown-item" href="#">和歌山</a></li>
            </ul>
          </div>
          <div class="dropdown">
            <button type="button" class="btn dropdown-toggle" id="dropdownMenuButton6" data-bs-toggle="dropdown" aria-expanded="false">中国/四国</button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton6">
              <li><a class="dropdown-item" href="#">鳥取</a></li>
              <li><a class="dropdown-item" href="#">島根</a></li>
              <li><a class="dropdown-item" href="#">岡山</a></li>
              <li><a class="dropdown-item" href="#">広島</a></li>
              <li><a class="dropdown-item" href="#">山口</a></li>
              <li><a class="dropdown-item" href="#">徳島</a></li>
              <li><a class="dropdown-item" href="#">香川</a></li>
              <li><a class="dropdown-item" href="#">愛媛</a></li>
              <li><a class="dropdown-item" href="#">高知</a></li>
            </ul>
          </div>
          <div class="dropdown">
            <button type="button" class="btn dropdown-toggle" id="dropdownMenuButton7" data-bs-toggle="dropdown" aria-expanded="false">九州</button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton7">
              <li><a class="dropdown-item" href="#">福岡</a></li>
              <li><a class="dropdown-item" href="#">佐賀</a></li>
              <li><a class="dropdown-item" href="#">長崎</a></li>
              <li><a class="dropdown-item" href="#">熊本</a></li>
              <li><a class="dropdown-item" href="#">大分</a></li>
              <li><a class="dropdown-item" href="#">宮崎</a></li>
              <li><a class="dropdown-item" href="#">鹿児島</a></li>
              <li><a class="dropdown-item" href="#">沖縄</a></li>
            </ul>
          </div>
          
        </div>
        <ul class="navbar-nav">
          <% if logged_in? %>
          <li class="nav-item"><%= link_to '口コミ一覧', posts_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.nickname %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'マイページ', user_path(current_user), class: 'dropdown-link' %></li>
              <li class="dropdown-item"><%= link_to 'ユーザー一覧', users_path, class: 'dropdown-link' %></li>
              <li class="dropdown-item"><%= link_to 'お気に入り一覧', likes_user_path(current_user), class: 'dropdown-link' %></li>
              
              <li class="dropdown-item"><%= link_to '新規作成', new_post_path, class: 'dropdown-link' %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-link' %></li>
            </ul>
          </li>
          <% else %>
            <li class="nav-item"><%= link_to '会員登録', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          <% end %>
          
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/posts/index.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'posts' %>
<% end %>

<div class="posts-index">
  <div class="container">
    <div class="new-title mb-4 py-4">
      <h1>最新クチコミ</h1>
    </div>
  </div>

  <div class="new-card">
    <div class="container">
      <div class="row d-flex align-items-start">
        <div class="row col-lg-9 m-0">
          <% @posts.each do |post| %>
              <div class="card-group">
                <div class="row card mb-3" style="max-width: 700px;">
                  <div class="row no-gutters pr-0">
                      <div class="col-4 my-auto">
                      <% if post.portraits.attached? %>
                          <%= image_tag post.portraits[0].variant(resize_to_limit: [300, 200]), class: 'card-img-top' %>
                      <% end %>
                      </div>
                      <!-- カードbody -->
                      <div class="col-8 p-1 p-lg-2">
                        <div class="card-body p-0">
                          <div class="card-titleContent mb-1 mb-sm-4">
                            <%= link_to post.title, post_path(post), class: 'card-index-title' %>
                            <p class="card-content m-0"><%= post.subject %></p>
                          </div>  
                          <!-- カードuser -->
                          <div class="d-flex card-user m-0">
                            <div class="card-user-img">
                              <% if post.user.profile_image.attached? %>
                                <%= image_tag post.user.profile_image.variant(resize_to_limit: [200, 200]),  :class => "profile_image", :alt => 'プロフィール画像' %>
                              <% else %>
                                <%= image_tag "/assets/default.png", :class => "profile_image", :alt => 'プロフィール画像' %>
                              <% end %>
                              <div class="card-user-nickname"><%= post.user.nickname %></div>
                            </div>
                            <div class="card-user-time ms-auto p-md-2">
                              <% if current_user.like?(post) %>
                                <%= link_to post_favorites_path(post), method: :delete do %>
                                  <i class="fas fa-heart"></i>
                                <% end %>
                              <% else %>
                                <%= link_to post_favorites_path(post), method: :post do %>
                                  <i class="far fa-heart"></i>
                                <% end %>
                              <% end %>
                              <span class="favorite-icon mt-sm-2"><%= post.likers.count %></span>
                              <small class="text-muted"><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
                            <% if current_user == post.user %>
                              <%= link_to post, class: "btn btn-light btn-sm", method: :delete, data: { confirm: "本当に削除しますか？" } do %><i class="far fa-trash-alt"></i>
                              <% end %>
                            <% end %>
                            </div>
                          </div>
                          <!-- カードuser -->
                        </div>
                      </div>
                      <!-- カードbody 終了 -->
                  </div>
                </div><!-- row card 終了 -->
              </div><!-- カードgroup 終了 -->
          <% end %>
        </div>

        <div class="row sidebar text-center col-lg-3 mt-3 ml-md-auto">
          <div class="btn-group-verticalr">
            <div class="btn-group">
              <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">北海道</button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">北海道</a></li>
                </ul>
            </div>
            <div class="btn-group">
              <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">東北</button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">青森</a></li>
                  <li><a class="dropdown-item" href="#">岩手</a></li>
                  <li><a class="dropdown-item" href="#">宮城</a></li>
                  <li><a class="dropdown-item" href="#">秋田</a></li>
                  <li><a class="dropdown-item" href="#">山形</a></li>
                  <li><a class="dropdown-item" href="#">福島</a></li>
                </ul>
            </div>
            <div class="btn-group">
              <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">関東</button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">茨城</a></li>
                  <li><a class="dropdown-item" href="#">栃木</a></li>
                  <li><a class="dropdown-item" href="#">群馬</a></li>
                  <li><a class="dropdown-item" href="#">埼玉</a></li>
                  <li><a class="dropdown-item" href="#">千葉</a></li>
                  <li><a class="dropdown-item" href="#">東京</a></li>
                  <li><a class="dropdown-item" href="#">神奈川</a></li>
                </ul>
            </div>
            <div class="btn-group">
              <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">中部</button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">新潟</a></li>
                  <li><a class="dropdown-item" href="#">富山</a></li>
                  <li><a class="dropdown-item" href="#">石川</a></li>
                  <li><a class="dropdown-item" href="#">福井</a></li>
                  <li><a class="dropdown-item" href="#">山梨</a></li>
                  <li><a class="dropdown-item" href="#">長野</a></li>
                  <li><a class="dropdown-item" href="#">岐阜</a></li>
                  <li><a class="dropdown-item" href="#">静岡</a></li>
                  <li><a class="dropdown-item" href="#">愛知</a></li>
                </ul>
            </div>
            <div class="btn-group">
              <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">近畿</button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">三重</a></li>
                  <li><a class="dropdown-item" href="#">滋賀</a></li>
                  <li><a class="dropdown-item" href="#">京都</a></li>
                  <li><a class="dropdown-item" href="#">大阪</a></li>
                  <li><a class="dropdown-item" href="#">兵庫</a></li>
                  <li><a class="dropdown-item" href="#">奈良</a></li>
                  <li><a class="dropdown-item" href="#">和歌山</a></li>
                </ul>
            </div>
            <div class="btn-group dropup">
              <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">中国・四国</button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">鳥取</a></li>
                  <li><a class="dropdown-item" href="#">島根</a></li>
                  <li><a class="dropdown-item" href="#">岡山</a></li>
                  <li><a class="dropdown-item" href="#">広島</a></li>
                  <li><a class="dropdown-item" href="#">山口</a></li>
                  <li><a class="dropdown-item" href="#">徳島</a></li>
                  <li><a class="dropdown-item" href="#">香川</a></li>
                  <li><a class="dropdown-item" href="#">愛媛</a></li>
                  <li><a class="dropdown-item" href="#">高知</a></li>
                </ul>
            </div>
            <div class="btn-group dropup">
              <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown">九州</button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">福岡</a></li>
                  <li><a class="dropdown-item" href="#">佐賀</a></li>
                  <li><a class="dropdown-item" href="#">長崎</a></li>
                  <li><a class="dropdown-item" href="#">熊本</a></li>
                  <li><a class="dropdown-item" href="#">大分</a></li>
                  <li><a class="dropdown-item" href="#">宮崎</a></li>
                  <li><a class="dropdown-item" href="#">鹿児島</a></li>
                  <li><a class="dropdown-item" href="#">沖縄</a></li>
                </ul>
            </div>
          </div>
        </div>   
      </div>
      <div class="paginate">
        <%= paginate @posts %>
      </div>
      <hr>
      <div class="index-link my-4 py-4">
        <%= link_to 'トップページ', root_path, class: 'btn btn-outline-secondary active' %>
        <%= link_to '新規投稿', new_post_path, class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  </div>
  
</div>

app/views/users/show.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'user' %>
<% end %>
<% if @user.id == current_user.id %>
<!-- プロフィール -->
<div class="userShow">
  <div class="user">
    <div class="container">
      <h2 class="user-title my-4 py-4"><%= @user.nickname %><span>さんのマイページ</span></h2>
      <div class="row">
        <div class="user-image text-center col-md-5 my-2">
        <% if @user.profile_image.attached? %>
          <%= image_tag @user.profile_image.variant(resize_to_limit: [200, 200]),  :class => "profile_image", :alt => 'プロフィール画像' %>
        <% else %>
          <%= image_tag "/assets/default.png", :class => "profile_image", :alt => 'プロフィール画像' %>
        <% end %>
          <p class="mt-2">プロフィール画像</p>
        </div>
        <div class="username col-md-7 my-md-4">
          <p class="">ペンネーム：<%= @user.nickname %></p>
          <p class="">メールアドレス：<%= @user.email %></p>
          <%= link_to "プロフィール編集", edit_user_path(@user), class: 'btn btn-outline-success' %>
          <small class="username-favorites mx-3">投稿数<span><%= @user.posts.count %></span></small>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <!-- 投稿リスト -->
  <div class="post">
    <div class="container">
      <div class="row justify-content-between">
        <div class="post-index col-md-7 col-lg-6 my-4">
          <p>最新投稿一覧</p> 
          <div class="post-list">
            <ul class="list-group list-group-flush">
              <% @user.posts.each do |post| %>
                <li class="list-group-item list-group-item-action list-group-item-light">
                <div class="post-list-post">
                  <%= link_to post.title, post_path(post) %>
                </div> 
                <div class="post-list-right">
                  <%= link_to '編集', edit_post_path(post), class: 'btn btn-outline-success btn-sm' %>
                  <span class="post-list-favorite mt-2 mx-md-3"><i class="far fa-heart"></i></span>
                  <small class="post-list-time"><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></small>
                </div>  
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="post-index col-md-5 col-lg-5 my-4">
          <p>都道府県別</p> 
          <div class="post-list">
            <ul class="list-group list-group-flush">
              <li class="list-group-item d-flex justify-content-between align-items-center"><a href="#">東京</a>
                <span class="badge bg-secondary rounded-pill">0</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center"><a href="#">大阪</a>
                <span class="badge bg-secondary rounded-pill">0</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center"><a href="#">愛知</a>
                <span class="badge bg-secondary rounded-pill">0</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center"><a href="#">神奈川</a>
                <span class="badge bg-secondary rounded-pill">0</span>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center"><a href="#">北海道</a>
                <span class="badge bg-secondary rounded-pill">0</span>
              </li>
            </ul>
          </div>
        </div>
      </div> 
    </div>
  </div>
  <hr>
<% else %>
  <div class="container">
    <div class="error-message">
    <h3>本人のみ閲覧可能です。</h3>
    </div>
  </div>
<% end %>
  <div class="container">
    <div class="index-link my-3 py-4">
      <%= link_to 'トップページ', root_path, class: 'btn btn-outline-secondary active' %>
      <%= link_to '口コミ一覧', posts_path, class: 'btn btn-outline-secondary' %>
      <%= link_to '新規作成', new_post_path, class: 'btn btn-outline-secondary' %>
    </div>
  </div>
</div>

    
      